version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: simplex_pay_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: simplex_pay
    ports:
      - "5432:5432"
    volumes:
      - ./db/seed:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
