// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimplexPay.Infrastructure.Persistence;

#nullable disable

namespace SimplexPay.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806144250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimplexPay.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "CA",
                            Currency = "CAD",
                            Flag = "🇨🇦",
                            IsActive = true,
                            Name = "Canada",
                            NameFr = "Canada"
                        },
                        new
                        {
                            Code = "SN",
                            Currency = "XOF",
                            Flag = "🇸🇳",
                            IsActive = true,
                            Name = "Senegal",
                            NameFr = "Sénégal"
                        },
                        new
                        {
                            Code = "CI",
                            Currency = "XOF",
                            Flag = "🇨🇮",
                            IsActive = true,
                            Name = "Ivory Coast",
                            NameFr = "Côte d'Ivoire"
                        },
                        new
                        {
                            Code = "ML",
                            Currency = "XOF",
                            Flag = "🇲🇱",
                            IsActive = true,
                            Name = "Mali",
                            NameFr = "Mali"
                        },
                        new
                        {
                            Code = "BF",
                            Currency = "XOF",
                            Flag = "🇧🇫",
                            IsActive = true,
                            Name = "Burkina Faso",
                            NameFr = "Burkina Faso"
                        },
                        new
                        {
                            Code = "BJ",
                            Currency = "XOF",
                            Flag = "🇧🇯",
                            IsActive = true,
                            Name = "Benin",
                            NameFr = "Bénin"
                        },
                        new
                        {
                            Code = "NE",
                            Currency = "XOF",
                            Flag = "🇳🇪",
                            IsActive = true,
                            Name = "Niger",
                            NameFr = "Niger"
                        },
                        new
                        {
                            Code = "TG",
                            Currency = "XOF",
                            Flag = "🇹🇬",
                            IsActive = true,
                            Name = "Togo",
                            NameFr = "Togo"
                        },
                        new
                        {
                            Code = "GW",
                            Currency = "XOF",
                            Flag = "🇬🇼",
                            IsActive = true,
                            Name = "Guinea-Bissau",
                            NameFr = "Guinée-Bissau"
                        },
                        new
                        {
                            Code = "CM",
                            Currency = "XAF",
                            Flag = "🇨🇲",
                            IsActive = true,
                            Name = "Cameroon",
                            NameFr = "Cameroun"
                        },
                        new
                        {
                            Code = "TD",
                            Currency = "XAF",
                            Flag = "🇹🇩",
                            IsActive = true,
                            Name = "Chad",
                            NameFr = "Tchad"
                        },
                        new
                        {
                            Code = "CG",
                            Currency = "XAF",
                            Flag = "🇨🇬",
                            IsActive = true,
                            Name = "Congo",
                            NameFr = "Congo-Brazzaville"
                        },
                        new
                        {
                            Code = "GA",
                            Currency = "XAF",
                            Flag = "🇬🇦",
                            IsActive = true,
                            Name = "Gabon",
                            NameFr = "Gabon"
                        },
                        new
                        {
                            Code = "CF",
                            Currency = "XAF",
                            Flag = "🇨🇫",
                            IsActive = true,
                            Name = "Central African Republic",
                            NameFr = "RCA"
                        },
                        new
                        {
                            Code = "GQ",
                            Currency = "XAF",
                            Flag = "🇬🇶",
                            IsActive = true,
                            Name = "Equatorial Guinea",
                            NameFr = "Guinée Équatoriale"
                        });
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.CountryPaymentMethod", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.HasKey("CountryCode", "PaymentMethodId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("CountryPaymentMethods");

                    b.HasData(
                        new
                        {
                            CountryCode = "CA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "ML",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "ML",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000012"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "ML",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000013"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "ML",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "BF",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "BF",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "BF",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "BJ",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "BJ",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "BJ",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "NE",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "NE",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "TG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "TG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "TG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "GW",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GW",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "CM",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CM",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CM",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CM",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "TD",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "TD",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "CF",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GQ",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        });
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("AmountFilled")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromCountryCode");

                    b.HasIndex("ToCountryCode");

                    b.HasIndex("UserId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.OfferPaymentMethod", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("Side")
                        .HasColumnType("text");

                    b.HasKey("OfferId", "PaymentMethodId", "Side");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("OfferPaymentMethods");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Remise en main propre",
                            IsActive = true,
                            Name = "Cash",
                            Type = "Cash"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Virement Interac (Canada)",
                            IsActive = true,
                            Name = "Interac e-Transfer",
                            Type = "BankTransfer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Virement bancaire SWIFT/SEPA",
                            IsActive = true,
                            Name = "Virement bancaire",
                            Type = "BankTransfer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Mobile Money Wave",
                            IsActive = true,
                            Name = "Wave",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Mobile Money Orange Sénégal",
                            IsActive = true,
                            Name = "Orange Money Sénégal",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Description = "Mobile Money Free (Sénégal)",
                            IsActive = true,
                            Name = "Free Money",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Description = "MTN MoMo Côte d'Ivoire",
                            IsActive = true,
                            Name = "MTN Mobile Money CI",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Description = "Orange Money Côte d'Ivoire",
                            IsActive = true,
                            Name = "Orange Money CI",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Description = "Moov Money Côte d'Ivoire",
                            IsActive = true,
                            Name = "Moov Money CI",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Description = "MTN MoMo Cameroun",
                            IsActive = true,
                            Name = "MTN Mobile Money CM",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Description = "Orange Money Cameroun",
                            IsActive = true,
                            Name = "Orange Money CM",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Description = "Orange Money Mali",
                            IsActive = true,
                            Name = "Orange Money Mali",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Description = "Moov Money Mali",
                            IsActive = true,
                            Name = "Moov Money Mali",
                            Type = "MobileMoney"
                        });
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReviewedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedUserId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TransactionId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerPaymentProof")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisputeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlatformFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerPaymentProof")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OfferId");

                    b.HasIndex("SellerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.CountryPaymentMethod", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.Country", "Country")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Countries")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Offer", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.Country", "FromCountry")
                        .WithMany()
                        .HasForeignKey("FromCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.Country", "ToCountry")
                        .WithMany()
                        .HasForeignKey("ToCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.User", "User")
                        .WithMany("Offers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCountry");

                    b.Navigation("ToCountry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.OfferPaymentMethod", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.Offer", "Offer")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Review", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.User", "ReviewedUser")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("ReviewedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewedUser");

                    b.Navigation("Reviewer");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.Offer", "Offer")
                        .WithMany("Transactions")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Offer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Country", b =>
                {
                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Offer", b =>
                {
                    b.Navigation("PaymentMethods");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.User", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("ReviewsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
