// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimplexPay.Infrastructure.Persistence;

#nullable disable

namespace SimplexPay.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806184348_AddIsAdminToUser")]
    partial class AddIsAdminToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimplexPay.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "CA",
                            CurrencyCode = "CAD",
                            Flag = "🇨🇦",
                            IsActive = true,
                            Name = "Canada",
                            NameFr = "Canada"
                        },
                        new
                        {
                            Code = "SN",
                            CurrencyCode = "XOF",
                            Flag = "🇸🇳",
                            IsActive = true,
                            Name = "Senegal",
                            NameFr = "Sénégal"
                        },
                        new
                        {
                            Code = "CI",
                            CurrencyCode = "XOF",
                            Flag = "🇨🇮",
                            IsActive = true,
                            Name = "Ivory Coast",
                            NameFr = "Côte d'Ivoire"
                        },
                        new
                        {
                            Code = "ML",
                            CurrencyCode = "XOF",
                            Flag = "🇲🇱",
                            IsActive = true,
                            Name = "Mali",
                            NameFr = "Mali"
                        },
                        new
                        {
                            Code = "BF",
                            CurrencyCode = "XOF",
                            Flag = "🇧🇫",
                            IsActive = true,
                            Name = "Burkina Faso",
                            NameFr = "Burkina Faso"
                        },
                        new
                        {
                            Code = "BJ",
                            CurrencyCode = "XOF",
                            Flag = "🇧🇯",
                            IsActive = true,
                            Name = "Benin",
                            NameFr = "Bénin"
                        },
                        new
                        {
                            Code = "NE",
                            CurrencyCode = "XOF",
                            Flag = "🇳🇪",
                            IsActive = true,
                            Name = "Niger",
                            NameFr = "Niger"
                        },
                        new
                        {
                            Code = "TG",
                            CurrencyCode = "XOF",
                            Flag = "🇹🇬",
                            IsActive = true,
                            Name = "Togo",
                            NameFr = "Togo"
                        },
                        new
                        {
                            Code = "GW",
                            CurrencyCode = "XOF",
                            Flag = "🇬🇼",
                            IsActive = true,
                            Name = "Guinea-Bissau",
                            NameFr = "Guinée-Bissau"
                        },
                        new
                        {
                            Code = "CM",
                            CurrencyCode = "XAF",
                            Flag = "🇨🇲",
                            IsActive = true,
                            Name = "Cameroon",
                            NameFr = "Cameroun"
                        },
                        new
                        {
                            Code = "TD",
                            CurrencyCode = "XAF",
                            Flag = "🇹🇩",
                            IsActive = true,
                            Name = "Chad",
                            NameFr = "Tchad"
                        },
                        new
                        {
                            Code = "CG",
                            CurrencyCode = "XAF",
                            Flag = "🇨🇬",
                            IsActive = true,
                            Name = "Congo",
                            NameFr = "Congo-Brazzaville"
                        },
                        new
                        {
                            Code = "GA",
                            CurrencyCode = "XAF",
                            Flag = "🇬🇦",
                            IsActive = true,
                            Name = "Gabon",
                            NameFr = "Gabon"
                        },
                        new
                        {
                            Code = "CF",
                            CurrencyCode = "XAF",
                            Flag = "🇨🇫",
                            IsActive = true,
                            Name = "Central African Republic",
                            NameFr = "RCA"
                        },
                        new
                        {
                            Code = "GQ",
                            CurrencyCode = "XAF",
                            Flag = "🇬🇶",
                            IsActive = true,
                            Name = "Equatorial Guinea",
                            NameFr = "Guinée Équatoriale"
                        },
                        new
                        {
                            Code = "NG",
                            CurrencyCode = "NGN",
                            Flag = "🇳🇬",
                            IsActive = true,
                            Name = "Nigeria",
                            NameFr = "Nigeria"
                        },
                        new
                        {
                            Code = "GH",
                            CurrencyCode = "GHS",
                            Flag = "🇬🇭",
                            IsActive = true,
                            Name = "Ghana",
                            NameFr = "Ghana"
                        });
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.CountryPaymentMethod", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.HasKey("CountryCode", "PaymentMethodId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("CountryPaymentMethods");

                    b.HasData(
                        new
                        {
                            CountryCode = "CA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "SN",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "CI",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "ML",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "ML",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000012"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "ML",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000013"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "ML",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "BF",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "BF",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "BF",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "BJ",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "BJ",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "BJ",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "NE",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "NE",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "TG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "TG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "TG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "GW",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GW",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "CM",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CM",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CM",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CM",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "TD",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "TD",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "CG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GA",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "CF",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GQ",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "NG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "NG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000014"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "NG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000015"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "NG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000016"),
                            IsPopular = false
                        },
                        new
                        {
                            CountryCode = "NG",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000017"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GH",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GH",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000018"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GH",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000019"),
                            IsPopular = true
                        },
                        new
                        {
                            CountryCode = "GH",
                            PaymentMethodId = new Guid("10000000-0000-0000-0000-000000000020"),
                            IsPopular = false
                        });
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("AmountFilled")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("BuyCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("BuyCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("SellCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("SellCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuyCountryCode");

                    b.HasIndex("BuyCurrencyCode");

                    b.HasIndex("SellCountryCode");

                    b.HasIndex("UserId");

                    b.HasIndex("Type", "Status");

                    b.HasIndex("SellCurrencyCode", "BuyCurrencyCode", "Status");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.OfferPaymentMethod", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("Side")
                        .HasColumnType("text");

                    b.HasKey("OfferId", "PaymentMethodId", "Side");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("OfferPaymentMethods");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Remise en main propre",
                            IsActive = true,
                            Name = "Cash",
                            Type = "Cash"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Virement Interac (Canada)",
                            IsActive = true,
                            Name = "Interac e-Transfer",
                            Type = "BankTransfer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Virement SWIFT / bancaire",
                            IsActive = true,
                            Name = "Virement bancaire",
                            Type = "BankTransfer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Mobile Money Wave",
                            IsActive = true,
                            Name = "Wave",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Orange Money Sénégal",
                            IsActive = true,
                            Name = "Orange Money SN",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Description = "Free Money Sénégal",
                            IsActive = true,
                            Name = "Free Money",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Description = "MTN Mobile Money Côte d'Ivoire",
                            IsActive = true,
                            Name = "MTN MoMo CI",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Description = "Orange Money Côte d'Ivoire",
                            IsActive = true,
                            Name = "Orange Money CI",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Description = "Moov Money Côte d'Ivoire",
                            IsActive = true,
                            Name = "Moov Money CI",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Description = "MTN Mobile Money Cameroun",
                            IsActive = true,
                            Name = "MTN MoMo CM",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Description = "Orange Money Cameroun",
                            IsActive = true,
                            Name = "Orange Money CM",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Description = "Orange Money Mali",
                            IsActive = true,
                            Name = "Orange Money ML",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Description = "Moov Money Mali",
                            IsActive = true,
                            Name = "Moov Money ML",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Description = "OPay Nigeria",
                            IsActive = true,
                            Name = "OPay",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Description = "PalmPay Nigeria",
                            IsActive = true,
                            Name = "PalmPay",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Description = "MTN Mobile Money Nigeria",
                            IsActive = true,
                            Name = "MTN MoMo NG",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Description = "Virement bancaire Nigeria (GTB, Access, Zenith…)",
                            IsActive = true,
                            Name = "Virement bancaire NG",
                            Type = "BankTransfer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Description = "MTN Mobile Money Ghana",
                            IsActive = true,
                            Name = "MTN MoMo GH",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            Description = "Vodafone Cash Ghana",
                            IsActive = true,
                            Name = "Vodafone Cash GH",
                            Type = "MobileMoney"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            Description = "AirtelTigo Money Ghana",
                            IsActive = true,
                            Name = "AirtelTigo Money GH",
                            Type = "MobileMoney"
                        });
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReviewedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedUserId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TransactionId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.SupportedCurrency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("SupportedCurrencies");

                    b.HasData(
                        new
                        {
                            Code = "CAD",
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "Canadian Dollar",
                            NameFr = "Dollar canadien",
                            Symbol = "CA$",
                            Type = "Buy"
                        },
                        new
                        {
                            Code = "USD",
                            DecimalPlaces = 2,
                            IsActive = false,
                            Name = "US Dollar",
                            NameFr = "Dollar américain",
                            Symbol = "US$",
                            Type = "Buy"
                        },
                        new
                        {
                            Code = "EUR",
                            DecimalPlaces = 2,
                            IsActive = false,
                            Name = "Euro",
                            NameFr = "Euro",
                            Symbol = "€",
                            Type = "Buy"
                        },
                        new
                        {
                            Code = "XOF",
                            DecimalPlaces = 0,
                            IsActive = true,
                            Name = "West African CFA Franc",
                            NameFr = "Franc CFA BCEAO",
                            Symbol = "FCFA",
                            Type = "Sell"
                        },
                        new
                        {
                            Code = "XAF",
                            DecimalPlaces = 0,
                            IsActive = true,
                            Name = "Central African CFA Franc",
                            NameFr = "Franc CFA BEAC",
                            Symbol = "FCFA",
                            Type = "Sell"
                        },
                        new
                        {
                            Code = "NGN",
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "Nigerian Naira",
                            NameFr = "Naira nigérian",
                            Symbol = "₦",
                            Type = "Sell"
                        },
                        new
                        {
                            Code = "GHS",
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "Ghanaian Cedi",
                            NameFr = "Cedi ghanéen",
                            Symbol = "₵",
                            Type = "Sell"
                        });
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerPaymentProof")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisputeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlatformFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerPaymentProof")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OfferId");

                    b.HasIndex("SellerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Country", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.SupportedCurrency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.CountryPaymentMethod", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.Country", "Country")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Countries")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Offer", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.Country", "BuyCountry")
                        .WithMany()
                        .HasForeignKey("BuyCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.SupportedCurrency", "BuyCurrency")
                        .WithMany()
                        .HasForeignKey("BuyCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.Country", "SellCountry")
                        .WithMany()
                        .HasForeignKey("SellCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.SupportedCurrency", "SellCurrency")
                        .WithMany()
                        .HasForeignKey("SellCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.User", "User")
                        .WithMany("Offers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuyCountry");

                    b.Navigation("BuyCurrency");

                    b.Navigation("SellCountry");

                    b.Navigation("SellCurrency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.OfferPaymentMethod", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.Offer", "Offer")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Review", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.User", "ReviewedUser")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("ReviewedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewedUser");

                    b.Navigation("Reviewer");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("SimplexPay.Domain.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.Offer", "Offer")
                        .WithMany("Transactions")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimplexPay.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Offer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Country", b =>
                {
                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.Offer", b =>
                {
                    b.Navigation("PaymentMethods");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("SimplexPay.Domain.Entities.User", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
